// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RoleScope string

const (
	RoleScopeSYSTEM RoleScope = "SYSTEM"
	RoleScopeTENANT RoleScope = "TENANT"
)

func (e *RoleScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleScope(s)
	case string:
		*e = RoleScope(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleScope: %T", src)
	}
	return nil
}

type NullRoleScope struct {
	RoleScope RoleScope `json:"role_scope"`
	Valid     bool      `json:"valid"` // Valid is true if RoleScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleScope) Scan(value interface{}) error {
	if value == nil {
		ns.RoleScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleScope), nil
}

type RoleStatus string

const (
	RoleStatusACTIVE   RoleStatus = "ACTIVE"
	RoleStatusINACTIVE RoleStatus = "IN_ACTIVE"
)

func (e *RoleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleStatus(s)
	case string:
		*e = RoleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleStatus: %T", src)
	}
	return nil
}

type NullRoleStatus struct {
	RoleStatus RoleStatus `json:"role_status"`
	Valid      bool       `json:"valid"` // Valid is true if RoleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RoleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleStatus), nil
}

type TenantStatus string

const (
	TenantStatusACTIVE   TenantStatus = "ACTIVE"
	TenantStatusINACTIVE TenantStatus = "IN_ACTIVE"
	TenantStatusDELETED  TenantStatus = "DELETED"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type TenantUserStatus string

const (
	TenantUserStatusACTIVE   TenantUserStatus = "ACTIVE"
	TenantUserStatusINVITED  TenantUserStatus = "INVITED"
	TenantUserStatusINACTIVE TenantUserStatus = "IN_ACTIVE"
	TenantUserStatusREMOVED  TenantUserStatus = "REMOVED"
)

func (e *TenantUserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantUserStatus(s)
	case string:
		*e = TenantUserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantUserStatus: %T", src)
	}
	return nil
}

type NullTenantUserStatus struct {
	TenantUserStatus TenantUserStatus `json:"tenant_user_status"`
	Valid            bool             `json:"valid"` // Valid is true if TenantUserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantUserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantUserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantUserStatus), nil
}

type UserStatus string

const (
	UserStatusINVITED   UserStatus = "INVITED"
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusDISABLED  UserStatus = "DISABLED"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
	UserStatusDELETED   UserStatus = "DELETED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Permission struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Code        string           `json:"code"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ResetPassword struct {
	ID        pgtype.UUID      `json:"id"`
	Otp       string           `json:"otp"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UserID    pgtype.UUID      `json:"user_id"`
	UsedAt    pgtype.Timestamp `json:"used_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Role struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Code        string           `json:"code"`
	Description pgtype.Text      `json:"description"`
	Scope       NullRoleScope    `json:"scope"`
	Status      RoleStatus       `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type RolePermission struct {
	ID           pgtype.UUID `json:"id"`
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type Session struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	RefreshToken string           `json:"refresh_token"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	IpAddress    pgtype.Text      `json:"ip_address"`
	IsRevoked    bool             `json:"is_revoked"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	RevokedAt    pgtype.Timestamp `json:"revoked_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Tenant struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	IsActive    bool             `json:"isActive"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Status      TenantStatus     `json:"status"`
}

type TenantUser struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	TenantID  pgtype.UUID      `json:"tenant_id"`
	RoleID    pgtype.UUID      `json:"role_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Status    TenantUserStatus `json:"status"`
}

type User struct {
	ID                pgtype.UUID      `json:"id"`
	FirstName         string           `json:"first_name"`
	LastName          pgtype.Text      `json:"last_name"`
	EmailID           string           `json:"email_id"`
	HashPassword      string           `json:"hash_password"`
	ProfilePictureUrl pgtype.Text      `json:"profile_picture_url"`
	Status            UserStatus       `json:"status"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}
