// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckUserExistsByEmailId(ctx context.Context, emailID string) (bool, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTenantUser(ctx context.Context, arg CreateTenantUserParams) (TenantUser, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRoleByCode(ctx context.Context, code string) (Role, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
