// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantUser = `-- name: CreateTenantUser :one
INSERT INTO tenant_users (
  user_id,
  tenant_id,
  role_id
) VALUES (
  $1,
  $2,
  $3
) RETURNING id, user_id, tenant_id, role_id, created_at, updated_at, status
`

type CreateTenantUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	RoleID   pgtype.UUID `json:"role_id"`
}

func (q *Queries) CreateTenantUser(ctx context.Context, arg CreateTenantUserParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, createTenantUser, arg.UserID, arg.TenantID, arg.RoleID)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
