// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, user_name, email_id, hash_password, profile_picture_url) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, first_name, last_name, user_name, email_id, hash_password, profile_picture_url, status, created_at, updated_at
`

type CreateUserParams struct {
	FirstName         string      `json:"first_name"`
	LastName          pgtype.Text `json:"last_name"`
	UserName          string      `json:"user_name"`
	EmailID           string      `json:"email_id"`
	HashPassword      string      `json:"hash_password"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.UserName,
		arg.EmailID,
		arg.HashPassword,
		arg.ProfilePictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.UserName,
		&i.EmailID,
		&i.HashPassword,
		&i.ProfilePictureUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
