// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExistsByEmailId = `-- name: CheckUserExistsByEmailId :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE email_id = $1
)
`

func (q *Queries) CheckUserExistsByEmailId(ctx context.Context, emailID string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExistsByEmailId, emailID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, email_id, hash_password, profile_picture_url) VALUES ($1, $2, $3, $4, $5) RETURNING id, first_name, last_name, email_id, hash_password, profile_picture_url, status, created_at, updated_at
`

type CreateUserParams struct {
	FirstName         string      `json:"first_name"`
	LastName          pgtype.Text `json:"last_name"`
	EmailID           string      `json:"email_id"`
	HashPassword      string      `json:"hash_password"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.EmailID,
		arg.HashPassword,
		arg.ProfilePictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.EmailID,
		&i.HashPassword,
		&i.ProfilePictureUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailId = `-- name: GetUserByEmailId :one
SELECT id, first_name, last_name, email_id, hash_password, profile_picture_url, status, created_at, updated_at FROM users WHERE email_id = $1 LIMIT 1
`

func (q *Queries) GetUserByEmailId(ctx context.Context, emailID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailId, emailID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.EmailID,
		&i.HashPassword,
		&i.ProfilePictureUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
